services:
  runtime-base:
    build:
      context: .
      dockerfile: docker/Dockerfile.base
    image: runtime-base

  probiot_bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.probiot_bot
    depends_on:
      - runtime-base
    env_file:
      - .env
    volumes:
      - /root/projects/whisper.cpp/models:/app/whisper.cpp/models
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    restart: unless-stopped