use core::models::uniframe_studio::uniframe_studio::TurnstileVerifyResponse;
use tracing::{error, info};

pub async fn is_premium_user(_user_id: Option<&str>) -> bool {
    true
}

pub async fn verify_turnstile_token(
    token: &str,
) -> Result<bool, Box<dyn std::error::Error + Send + Sync>> {
    let secret_key = std::env::var("TURNSTILE_SECRET_KEY")
        .map_err(|_| "TURNSTILE_SECRET_KEY not found in environment")?;

    let client = reqwest::Client::new();

    let response = client
        .post("https://challenges.cloudflare.com/turnstile/v0/siteverify")
        .header("Content-Type", "application/x-www-form-urlencoded")
        .form(&[("secret", secret_key.as_str()), ("response", token)])
        .send()
        .await?;

    if !response.status().is_success() {
        return Err(format!("Turnstile API returned status: {}", response.status()).into());
    }

    let verify_response: TurnstileVerifyResponse = response.json().await?;

    if !verify_response.success {
        if let Some(errors) = verify_response.error_codes {
            error!("Turnstile verification failed with errors: {:?}", errors);
        }
    }

    Ok(verify_response.success)
}

pub(crate) async fn send_idea_email(idea_text: &str) -> anyhow::Result<()> {
    let api_key = std::env::var("BREVO_API_KEY")?;
    let admin_email = match std::env::var("ADMIN_EMAIL") {
        Ok(email) => email,
        Err(_) => {
            error!("ADMIN_EMAIL not set - cannot send idea notifications");
            return Ok(());
        }
    };

    let client = reqwest::Client::new();

    let formatted_idea = idea_text
        .chars()
        .take(1000)
        .collect::<String>()
        .replace('\n', "<br>")
        .replace('<', "&lt;")
        .replace('>', "&gt;");

    let subject = "💡 New Idea Submission - Uniframe Studio".to_string();

    let text_content = format!(
        "New idea submission received!\n\n\
        Idea:\n{}\n\n\
        Timestamp: {}\n\n\
        ---\n\
        Uniframe Studio Ideas System",
        idea_text,
        chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
    );

    let html_content = format!(
        r#"
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>New Idea Submission</title>
        </head>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px;">
                <h1 style="color: white; margin: 0; font-size: 28px;">💡 New Idea Received!</h1>
                <p style="color: #f0f0f0; margin: 10px 0 0 0; font-size: 16px;">Uniframe Studio Ideas System</p>
            </div>
            
            <div style="background: #f8f9fa; border-radius: 8px; padding: 25px; margin-bottom: 20px;">
                <h2 style="color: #495057; margin-top: 0; font-size: 20px; border-bottom: 2px solid #dee2e6; padding-bottom: 10px;">💭 Idea Content</h2>
                <div style="background: white; padding: 20px; border-radius: 6px; border-left: 4px solid #667eea; margin: 15px 0;">
                    <p style="margin: 0; font-size: 16px; white-space: pre-wrap;">{}</p>
                </div>
            </div>

            <div style="background: #e9ecef; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
                <h3 style="color: #495057; margin-top: 0; font-size: 16px;">📋 Submission Details</h3>
                <table style="width: 100%; border-collapse: collapse;">
                    <tr>
                        <td style="padding: 8px 0; font-weight: bold; color: #6c757d;">Timestamp:</td>
                        <td style="padding: 8px 0; color: #495057;">{}</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 0; font-weight: bold; color: #6c757d;">Characters:</td>
                        <td style="padding: 8px 0; color: #495057;">{} / 1000</td>
                    </tr>
                </table>
            </div>

            <div style="text-align: center; padding: 20px; color: #6c757d; font-size: 14px; border-top: 1px solid #dee2e6;">
                <p style="margin: 0;">This email was automatically generated by Uniframe Studio Ideas System</p>
                <p style="margin: 5px 0 0 0;">🎬 Making video dubbing accessible to everyone</p>
            </div>
        </body>
        </html>
        "#,
        formatted_idea,
        chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC"),
        idea_text.len()
    );

    let response = client
        .post("https://api.brevo.com/v3/smtp/email")
        .header("api-key", api_key)
        .header("Content-Type", "application/json")
        .json(&serde_json::json!({
            "sender": {"email": "noreply@uniframe-studio.com", "name": "Uniframe Studio Ideas"},
            "to": [{"email": admin_email}],
            "subject": subject,
            "textContent": text_content,
            "htmlContent": html_content
        }))
        .send()
        .await?;

    if response.status().is_success() {
        info!("Idea email sent successfully to admin");
        Ok(())
    } else {
        let error_text = response.text().await?;
        error!("Failed to send idea email: {}", error_text);
        Err(anyhow::anyhow!("Idea email sending failed: {}", error_text))
    }
}
