FROM bot_foundry_base

USER 1001:1000

COPY common_res/messages/common /app/common_res/messages/common
COPY common_res/messages/groot_bot /app/common_res/messages/groot_bot
COPY common_res/system_roles/groot_bot /app/common_res/system_roles/groot_bot

ENV APP_NAME="groot_bot"
ENV WHISPER_MODEL_PATH="/app/whisper.cpp/models/ggml-base.bin"