FROM rust:latest AS builder

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl3 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY Cargo.toml Cargo.lock ./

COPY core core/
COPY the_forge the_forge/
COPY bot_foundry bot_foundry/
COPY agent_foundry agent_foundry/
COPY tools tools/

RUN cargo build -p agent_foundry --release -j 4

FROM debian:bookworm-slim AS agent_foundry_base

RUN apt-get update && apt-get install -y \
    ca-certificates \
    libssl3 \
    openssl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /usr/src/app/target/release/agent_foundry .

RUN mkdir -p tmp && \
    chown 1001:1000 tmp && \
    chmod 700 tmp && \
    chown 1001:1000 /app && \
    chmod 755 /app

COPY docker/agent_foundry_entrypoint.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh

USER 1001:1000

ENTRYPOINT ["./entrypoint.sh"]