FROM bot_foundry_base

USER root

COPY common_res/messages/common /app/common_res/messages/common
COPY common_res/messages/probiot_bot /app/common_res/messages/probiot_bot
COPY common_res/system_roles/probiot /app/common_res/system_roles/probiot

COPY docker/entrypoint.sh .
RUN chmod +x entrypoint.sh

USER 1001:1000

ENV APP_NAME="probiot_bot"
ENV WHISPER_MODEL_PATH="/app/whisper.cpp/models/ggml-base.bin"
ENTRYPOINT ["./entrypoint.sh"]