FROM bot_foundry_base

USER root

COPY --chown=1001:1000 common_res/messages/common /app/common_res/messages/common
COPY --chown=1001:1000 common_res/messages/groot_bot /app/common_res/messages/groot_bot
COPY --chown=1001:1000 common_res/system_roles/groot_bot /app/common_res/system_roles/groot_bot

USER 1001:1000

ENV APP_NAME="groot_bot"
ENV WHISPER_MODEL_PATH="/app/whisper.cpp/models/ggml-base.bin"